# application-local.yml
spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/BloomingShop?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: psw
    password: psw123123!
  servlet:
    multipart:
      location: C:/bloomingshop # 로컬 경로 설정
file:
  product-dir: C:/bloomingshop/product
  support-dir: C:/bloomingshop/support
